# Generated by Django 5.0.6 on 2024-06-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_remove_employee_postion_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
